### ISSUE TITLE
Encoding fails with org.daisy.pipeline.core.script.ScriptValidationException:  System error: Chain not XML valid

### ISSUE THREAD

**Issue by egli** [sbsdev/mdr2#35]
from the log:

```
2015-04-23 08:47:16,376 INFO  [mdr2.encode] (Thread-1395 (HornetQ-client-global-threads-1692545651)) Encoding 20113 (1) with bitrate: 128
2015-04-23 08:47:16,378 DEBUG [mdr2.encode] (Thread-1395 (HornetQ-client-global-threads-1692545651)) Encoding 20113 (1) with 128, /var/lib/mdr2/recorded/20113/ncc.html, /var/lib/mdr2/encoded/20113/1, mono, 22050
2015-04-23 08:47:18,218 ERROR [mdr2.encode] (Thread-1395 (HornetQ-client-global-threads-1692545651)) Encoding of 20113 (1) failed with exit 1 and message "org.daisy.pipeline.core.script.ScriptValidationException:\
 System error: Chain not XML valid
        at org.daisy.pipeline.core.script.Creator.newScript(Creator.java:67)
        at org.daisy.pipeline.core.PipelineCore.newScript(PipelineCore.java:270)
        at org.daisy.pipeline.ui.CommandLineUI.main(CommandLineUI.java:184)
"
2015-04-23 08:48:27,488 WARN  [org.hornetq.jms.client] (Thread-1396 (HornetQ-client-global-threads-1692545651)) HQ122001: Unhandled exception thrown from onMessage: java.lang.RuntimeException: Unexpected error ha\
ndling message
        at org.projectodd.wunderboss.messaging.hornetq.JMSListener.onMessage(JMSListener.java:86) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.hornetq.jms.client.HornetQJMSConsumer$MessageListenerWrapper.onMessage(HornetQJMSConsumer.java:190) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.hornetq.jms.client.JMSMessageListenerWrapper.onMessage(JMSMessageListenerWrapper.java:103) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.hornetq.core.client.impl.ClientConsumerImpl.callOnMessage(ClientConsumerImpl.java:1116) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.hornetq.core.client.impl.ClientConsumerImpl.access$500(ClientConsumerImpl.java:56) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.hornetq.core.client.impl.ClientConsumerImpl$Runner.run(ClientConsumerImpl.java:1251) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.hornetq.utils.OrderedExecutorFactory$OrderedExecutor$1.run(OrderedExecutorFactory.java:104) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_75]
Caused by: java.lang.IllegalArgumentException: /var/lib/mdr2/iso/20113/1/20113.iso not found
        at me.raynes.fs$assert_exists.invoke(fs.clj:299) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at me.raynes.fs$copy.invoke(fs.clj:304) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at me.raynes.fs$copy_PLUS_.invoke(fs.clj:459) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at mdr2.archive$fn__12892$fn__12893.invoke(archive.clj:209) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.lang.AFn.call(AFn.java:18) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.projectodd.wunderboss.transactions.NarayanaTransaction.begin(NarayanaTransaction.java:115) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.projectodd.wunderboss.transactions.NarayanaTransaction.required(NarayanaTransaction.java:33) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at mdr2.archive$fn__12892.invoke(archive.clj:191) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.lang.MultiFn.invoke(MultiFn.java:227) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at mdr2.main$_main$fn__16242.invoke(main.clj:24) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at immutant.messaging.internal$message_handler$fn__3804.invoke(internal.clj:112) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.lang.AFn.applyTo(AFn.java:144) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.core$apply.invoke(core.clj:624) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.lang.RestFn.applyTo(RestFn.java:142) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.core$apply.invoke(core.clj:628) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.core$bound_fn_STAR_$fn__4140.doInvoke(core.clj:1884) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at clojure.lang.RestFn.invoke(RestFn.java:408) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at immutant.messaging.internal$message_handler$reify__3806.onMessage(internal.clj:120) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        at org.projectodd.wunderboss.messaging.hornetq.JMSListener.onMessage(JMSListener.java:78) [mdr2-0.3.0-SNAPSHOT-standalone.jar:]
        ... 9 more

```

**Comment by egli** [comment]
Rerunning the same code works fine. This was probably a side effect of having no space left on the device at the time
